function Solutions(answer, clue) {
  const solutions = {
    COOLASA: "cucumber",
    PLAYEAR: "play it by the ear",
    OLDBLOC: "chip off the old block, K",
    AXLXEXG: "break a leg",
    FABLUCE: "blue in the face",
    TNNLITE: "light at end of the tunnel",
    AOFASAP: "as",
    NROFPNR: "no record",
    HOFOSHA: "health",
    FOFSPCA: "for",
    GOFKISS: "gene",
    IOFIRMA: "eye",
    "7TIMES8": "56",
    AAADDBB: "CC",
    "9CHOOS5": "126",
    "4XPIRRR": "/3",
    TENMODE: "10-3e",
    ISQUARD: "-1",
    PRINTJS: "console.log",
    SERPENT: "python",
    "PRNTC++": "std::cout",
    "BOAF(X)": "def",
    TETANUS: "rust",
    CHECKRS: "go",
    "JULIET&": "romeo",
    THEGR8J: "the great gatsby",
    "2B|!2B": "hamlet",
    READERI: "jane eyre",
    BESTOFX: "a tale of two cities",
    NOTINKS: "wizard of oz",
    BIGAPPL: "NYC",
    SINCITY: "Vegas",
    BALTICC: "Baltic Sea",
    BIGHOLE: "Grand Canyon",
    REFUSAL: "the Nile",
    ESPRSSO: "Java",
    LETOAST: "French toast",
    LAGRIPE: "Spanish flu",
    MUFFINS: "English muffins",
    FORNUIS: "Dutch oven",
    PAIPIKA: "Hawaiian pizza",
    WENQUAN: "Japanese onsen",
    ROYGBIV: "7 colors, rainbow",
    "SNOWYT&": "7 dwarves",
    CCCCCCC: "7 seas",
    NOEARTH: "7 planets",
    ENDSINY: "days of the week",
    FASTSIN: "7 minutes in heaven",
  };

  return solutions[clue] === answer.toLowerCase(); //return a boolean based on if user got the answer right or not
}

export default Solutions;
